### ISSUE TITLE
Add Items Last-Updated Changes to Alma OAI Harvesting Last-Updated date checks

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/tul_cob#1114]
Research if Item-level changes need to trigger OAI indexing of the records, or if item-level information is access by TUL COB via a different mechanism than Solr queries.

If Item-level changes need to trigger OAI indexing of the records, 
- [x] add Item-level 'last_updated' dates to the Alma OAI Publication profile;
- [x] update traject mapping / config to parse item-level ADMb fields as well for creating data written to Solr (see #1113 tulibraries/cob_datapipeline#45)

**Comment by cmharlow** [comment]
See fields to be added here: https://tulibdev.atlassian.net/browse/BL-875 @dkinzer is working on upstream ticket; see if he can't fit second part of this work on that PR.

**Comment by dkinzer** [comment]
@cmharlow ITMupdated field has been added to the PR.

**Comment by cmharlow** [comment]
completed by #1153 awaiting deployment

**Comment by dkinzer** [comment]
Scheduled for deployment
