### ISSUE TITLE
Add databases az solr configuration

### ISSUE THREAD

**Issue by dkinzer** [tulibraries/tul_cob#1143]
Relates to: https://github.com/tulibraries/tul_cob_playbook/issues/58

We need to add a databases-az specific solr configurations instead of using the catalog configuration.

**Comment by cmharlow** [comment]
@dkinzer you're already doing this 9have already done this?) for the existing solr / tul_cob setup, at least up to QA, right?

**Comment by dkinzer** [comment]
@cmharlow Not yet... we're still using just basically a copy of catalog.

**Comment by cmharlow** [comment]
@dkinzer thanks for the update. should i leave in the to be done column then?

**Comment by dkinzer** [comment]
Yup, this is still a TODO... low priority I guess because things working without this step... but still something I worry about a little.

**Comment by dkinzer** [comment]
done https://github.com/tulibraries/tul_cob-az-solr
