### ISSUE TITLE
prod deploy

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/tul_cob#1407]
Error in the assets:precompile step `2019-08-29T08:59:56.276632 #30879]  INFO -- : Writing /var/www/tul_cob/public/assets/fb-63b1f9b0d4603e6613e7335cda5a6797bed85746182cd5c277051d2405671fe4.png\\nI, [2019-08-2close failed in file object destructor:\r\nsys.excepthook is missing\r\nlost sys.stderr\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

Need to check logs + possibly run prod deploy manually / with ansible verbose on to see whats going on.

**Comment by dkinzer** [comment]
Not seeing this error anymore.
