### ISSUE TITLE
Fix ReadME.md

### ISSUE THREAD

**Issue by sensei100** [tulibraries/tul_cob#34]
I ran into a couple of problems when following along in the README.  

1. I think that these two lines need to be switched.  It didn't work for me to run db:migrate first.
bundle exec rails db:migrate
cp config/secrets.yml.exmaple config/secrets.yml

2. There is a typo:
cp config/secrets.yml.exmaple config/secrets.yml 

should be

cp config/secrets.yml.example config/secrets.yml

3. Expand the directions on how to untar the sample data.

**Comment by bibliotechy** [comment]
Closed by #38
