### ISSUE TITLE
Why is `tag: :div` passed to render_index_doc_actions?

### ISSUE THREAD

**Issue by jcoyne** [tulibraries/tul_cob#3488]
I was looking at this code https://github.com/tulibraries/tul_cob/blob/3469c4aae69ae7a383c8759be19d9c78e79f7b09/app/views/catalog/_index_header.html.erb#L20 and I couldn't figure out why the `tag:` argument is passed. Do you know what that is used for?

**Comment by dkinzer** [comment]
@jcoyne thanks for pointing this out to us.  I think that's a mistake probably made because it's one of the named parameters that the underlying component defines in the the 7.x branch: https://github.com/projectblacklight/blacklight/blob/93424b91dcd97b0aff33ee43ab72cb9366a84193/app/components/blacklight/document/actions_component.rb#L14

**Comment by jcoyne** [comment]
@dkinzer I'm not sure that would make it to that part though. I think it would have ended up in the `options`, kwarg.

**Comment by dkinzer** [comment]
Hmm it does make it into options ... but beyond that I don't know if anything picks it up.  I'll see what happens in a debug session.

**Comment by dkinzer** [comment]
@jcoyne Oh, I see what you are saying.  Yes. I agree with you.  I think it's an error but I was trying to reason out why the error got made in the first place.  I'm pretty sure it's an error. But just to be extra carful I'm going to try breaking my local by replacing with something else.

**Comment by dkinzer** [comment]
OK I verified that it's going into options and from there it's not really getting used anywhere. Updating in my local to be `tag: h1` caused no changes in any of the action views.  So I do think it's just a mistake or maybe a template that no longer gets used.
